name: Test workflow
on:
  schedule:
    - cron: "5 * * * *"

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v4

      - name: download m3upt
        run: sh test/test.sh

      - name: setup git config
        run: |
          git config user.name "🚀 HAL 9000"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          cd test && git add *.m3u
          git commit -m "Update streams"
          git push origin main
